language: node_js

node_js:
  - '8.9'

cache:
  directories:
    - node_modules

sudo: false

branches:
  except:
    - gh-pages

deploy:
  skip_cleanup: true
  provider: script
  script: npm run gulp publish
  on:
    branch: master

